
[workspace]
resolver = "2"

members = [
    "scripts", 
    "experimental/*",
    "installations/*",
    "pitopi", 
    "controllers", 
    "bittide", 
    "bittide-impls", 
    "bitsurf", 
    ]

[workspace.package]
rust-version = "1.81"