
[workspace]
resolver = "2"

members = [
    "scripts",
    "experimental/*",
    "installations/*",
    "pitopi",
    "controllers",
    "bittide",
    "bittide-impls",
    "surf",
    "multibuild",
    "minsync",
]

[workspace.package]
rust-version = "1.81"
