[package]
name = "surf-proc"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full", "visit-mut", "extra-traits"] }

[lib]
proc-macro = true
