[package]
name = "bittide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
controllers = { path = "../controllers" }
heapless = { version = "0.8.0", features = ["defmt-03"] }
log = "0.4.22"
